name: .NET TEMPLATE
on:
  pull_request:
    branches: [ "main"]
  workflow_dispatch:  
  
jobs:
  quality:
    uses: Limasjg-Fly/.github/.github/workflows/sonar-default.yml@main
    with:
      secrets: inherit

#  build:
#   uses: Limasjg-Fly/.github/.github/workflows/dotnet-default.yml@main
