name: .NET TEMPLATE
on:
  pull_request:
    branches: [ "main"]
  workflow_dispatch:  
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run reusable workflow from Repo A
        uses: Limasjg-Fly/.github/.github/workflows/sonar-default.yml@main
        with:
          sonar_token: ${{ secrets.Sonar_token }}
